---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: example
  name: example-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: example-app
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-app
    spec:
      containers:
      - name: example-app
        image: stefanprodan/podinfo:6.5.3
---
kind: Service
apiVersion: v1
metadata:
  namespace: example
  name: example-service
spec:
  selector:
    app.kubernetes.io/name: example-app
  ports:
  - port: 9898
