---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: example
  name: example-local-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: example-local-app
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-local-app
    spec:
      containers:
      - name: example-local-app
        image: localhost:5001/example:latest
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  namespace: example
  name: example-local-service
spec:
  selector:
    app.kubernetes.io/name: example-local-app
  ports:
  - port: 80
